import os
from pathlib import Path

from src.exception import CustomException
from src.paths import ARTIFACTS_PATH
from src.utils import load_object


class PredictPipeline():
    '''
    Pipeline to evaluate if a text was generated by an human or AI.
    '''

    def __init__(self):
        self.__load_objects()

    def __load_objects(self):
        '''
        Helper function to load model and preprocessor.
        '''

        model_path = Path(ARTIFACTS_PATH) / 'model.pkl'
        preprocessor_path = Path(ARTIFACTS_PATH) / 'preprocessor.pkl'

        self.model = load_object(file_path=model_path)
        self.preprocessor = load_object(file_path=preprocessor_path)

    def predict_proba(self, documents):
        '''
        Function to predict the probability of the given documents were generated by an AI.

        Parameters
        ---
        * documents: list of documents (texts) to predict the probability.
        
        Returns
        ---
        * list of probabilities.
        '''

        try:
            # preprocess texts
            prepeocessed_data = self.preprocessor.transform(documents)

            # predict probas
            probas = self.model.predict_proba(prepeocessed_data)[:, 1]

            return probas
        
        except Exception as e:
            raise CustomException(e)
        
    def predict_single_document(self, document):
        '''
        Function to predict the probability of the given document was generated by an AI.

        Parameters
        ---
        * document: document (text) to predict the probability.
        
        Returns
        ---
        * single probability.
        '''

        try:
            proba = self.predict_proba([document])[0]
            return proba

        except Exception as e:
            raise CustomException(e)
        
    def predict_sentences_proba(self, document):
        '''
        Function to predict the probability of the given document sentences were generated by an AI.

        Parameters
        ---
        * document: document (text) to predict the probability.
        
        Returns
        ---
        * list of sentences and their probabilities.
        '''

        try:
            # get model text preprocessing
            text_preprocessing = self.preprocessor['text_preprocessing']

            # get spacy nlp object
            nlp = text_preprocessing.nlp

            # activate sentencizer component
            nlp.add_pipe('sentencizer')

            # get documnet sentences
            doc = nlp(document)
            sents = [sent.text for sent in doc.sents]

            # deactivate sentencizer component
            nlp.remove_pipe('sentencizer')

            # calculates probabilities
            probas = self.predict_proba(sents)

            return zip(sents, probas)

        except Exception as e:
            raise CustomException(e)